name: CI Tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * SUN"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04, ruby: head }
    name: test ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Install dependencies
        run: |
          sudo apt install -qq build-essential musl-dev musl-tools
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Compile
        run: |
          rake run:build
      - name: Test
        run: |
          rake run:test
